apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
      version: v1
  template:
    metadata:
      labels:
        app: spring-app
        version: v1
    spec:
      containers:
        - name: spring-container
          image: spring-app:1
          imagePullPolicy: IfNotPresent