version: '3.3'
services:
  data:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=this
    ports:
      - 3306:3306
  app:
    depends_on:
      - data
    image: spring-app:1
    restart: on-failure
    ports:
      - 8888:8888
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://data:3306/this",
        "spring.datasource.username":"root",
        "spring.datasource.password":"root123",
        "spring.jpa.hibernate.ddl-auto":"update",
        "spring.jpa.show-sql":"true"
      }'